###
POST http://localhost:9000/api/users HTTP/1.1
content-type: application/json

{
    "name":"Maria Gamarra",
    "email":"MariaGamarra@gmail.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJsb3RsIiwiZW1haWwiOiJsb3RsQGdtYWlsLmNvbSIsIl9pZCI6IjY0OGNjNDAxYjkzZDc3MjE5NWZlOTE5ZiJ9LCJpYXQiOjE2ODY5NDY4MTd9.hL_meoAbsdzWnTNGZ4IeXbD8S5iHO702AjvwJfMBCBI
###
GET http://localhost:9000/api/users/648b32e60fdabe97ae3d8dd6 HTTP/1.1

###
PUT   http://localhost:9000/api/users/648b32e60fdabe97ae3d8dd6 HTTP/1.1
content-type: application/json

{
    "name": "Milagros Salazar",    
    "email":"salazargamarraa@gmail.com"
}

###
DELETE http://localhost:9000/api/users/648b32e60fdabe97ae3d8dd6 HTTP/1.1